version: "3"
services:
        urlwatch:
                image: easypi/urlwatch
                volumes:
                        - ./data:/root/.urlwatch
                        - ./data/crontab:/etc/crontabs/root
                restart: unless-stopped
